### ISSUE TITLE
Overcoming VNet peering limits - Mention that NVAs are required

### ISSUE THREAD

**Issue by marcelkmfst** [MicrosoftDocs/architecture-center.de-de#3]
Hi,

under Overcoming VNet peering limits, the Spoke-Hub-Hub model is mentioned. I strongly recommend that you mention that NVAs for Routing are required deployed in the Spoke-Hub as transient routing is not supported. I had a customer who implemented that model based on this arcticle and now they recognized that NVAs are required. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementieren einer Hub-Spoke-Netzwerktopologie in Azure - Azure Reference Architectures](https://docs.microsoft.com/de-de/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center.de-de/blob/live/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hello, @marcelkmfst 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/architecture-center/issues/1387

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
