### ISSUE TITLE
Kappa diagram has wrong labels?

### ISSUE THREAD

**Issue by tconrady** [MicrosoftDocs/architecture-center.de-de#5]
The Kappa diagram shows the 'Speed layer' contains the 'Master data' and the 'Long-term store' contains the 'Real-time views'. Shouldn't it be the other way around?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 953d7d0d-651f-a566-1d28-6946c824e1ae
* Version Independent ID: 8f5b4264-dcc9-ad28-36fe-45463d15f52a
* Content: [Big Data-Architekturen](https://docs.microsoft.com/de-de/azure/architecture/data-guide/big-data/#feedback)
* Content Source: [docs/data-guide/big-data/index.md](https://github.com/microsoftdocs/architecture-center.de-DE/blob/live/docs/data-guide/big-data/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hello, @tconrady

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://docs.microsoft.com/de-de/azure/architecture/data-guide/big-data/#feedback

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
