### ISSUE TITLE
Status of QUIC and HTTP/3

### ISSUE THREAD

**Issue by git001** [MicrosoftDocs/architecture-center.de-de#6]
Do you plan to offer also QUIC & HTTP/3 in your loadbalancers?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Übersicht über Azure-Lastenausgleichsoptionen - Azure Application Architecture Guide](https://docs.microsoft.com/de-de/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center.de-DE/blob/live/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @sharad4u
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @git001
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @git001 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here -https://github.com/MicrosoftDocs/architecture-center/issues/1878

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
